# Generated by Django 2.2.5 on 2021-02-01 18:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='color',
            field=colorfield.fields.ColorField(default='#3aafd2', max_length=18),
        ),
    ]
