# Generated by Django 3.2.23 on 2024-01-13 20:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20210202_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
