# Generated by Django 2.2.5 on 2019-12-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurable_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerconfigurablemenuitem',
            name='patner_menu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='configurable_menu.PartnerConfigurableMenu'),
            preserve_default=False,
        ),
    ]
