# Generated by Django 2.2.5 on 2020-01-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
        ('configurable_menu', '0002_partnerconfigurablemenuitem_patner_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerconfigurablemenu',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partner_menus', to='partner.Partner'),
            preserve_default=False,
        ),
    ]
