# Generated by Django 2.2.5 on 2020-05-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurable_menu', '0004_partnerconfigurablemenuitem_included_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerconfigurablemenu',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnerconfigurablemenu',
            name='site',
        ),
    ]
