# Generated by Django 3.2.23 on 2024-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurable_menu', '0006_auto_20210225_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerconfigurablemenuitem',
            name='ancestors_are_public',
            field=models.BooleanField(db_index=True, default=True, help_text='The ancestors of this category are public', verbose_name='Ancestor categories are public'),
        ),
        migrations.AddField(
            model_name='partnerconfigurablemenuitem',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this category in search results and catalogue listings.', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='partnerconfigurablemenuitem',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='partnerconfigurablemenuitem',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='partnerconfigurablemenuitem',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
    ]
