# Generated by Django 3.2.25 on 2024-07-11 11:34

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configurable_menu', '0007_auto_20240113_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerconfigurablemenuitem',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
