# Generated by Django 3.2.25 on 2024-08-07 16:24

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20240113_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='attributeoptiongroup',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
