# Generated by Django 2.2.5 on 2020-05-29 20:31

from django.db import migrations, models

import apps.dashboard.settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_setting_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo_size',
            field=models.CharField(default='100x100', help_text='Please enter image dimensions not more then 255 characters.', max_length=255, verbose_name='Logo Dimension (height x width)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to=apps.dashboard.settings.models.get_tenant_specific_upload_folder, verbose_name='Store Logo'),
        ),
    ]
