# Generated by Django 2.2.5 on 2021-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20200529_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='store_from_email',
            field=models.EmailField(blank=True, help_text='Please enter email address from you want to send email messages to your customers.', max_length=254, null=True, verbose_name='From e-mail address.'),
        ),
    ]
