# Generated by Django 2.2.5 on 2021-02-02 14:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_setting_store_from_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='setting',
            managers=[
                ('effective_settings', django.db.models.manager.Manager()),
            ],
        ),
    ]
