# Generated by Django 2.2.5 on 2021-02-02 14:02

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_setting_store_from_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='setting',
            managers=[
                ('effective_settings', django.db.models.manager.Manager()),
            ],
        ),
    ]
