# Generated by Django 2.2.5 on 2021-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20210202_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='store_phone_number',
            field=models.CharField(blank=True, help_text='Please enter support contact number.', max_length=50, null=True, verbose_name='Store support contact number.'),
        ),
    ]
