# Generated by Django 2.2.5 on 2020-03-06 09:30
from datetime import datetime, timedelta

from django.contrib.sites.models import Site
from django.db import migrations

from multitenancy.models import Tenant, Domain


def add_default_tenant(apps, schema_editor):
    tenants = [
        dict(tenant=dict(schema_name='primzel', name='primzel', paid_until=datetime.now() + timedelta(days=30),
                         on_trial=True),
             domain='primzel.localhost', template_folder='primzel.localhost'),
        dict(tenant=dict(schema_name='hoko', name='hoko.pk', paid_until=datetime.now() + timedelta(days=30),
                         on_trial=True),
             domain='hoko.localhost', template_folder='hoko.local'),
        dict(tenant=dict(schema_name='example', name='example.com', paid_until=datetime.now() + timedelta(days=30),
                         on_trial=True),
             domain='example.com', template_folder='example.com'),
        dict(tenant=dict(schema_name='localhost_db', name='localhost', paid_until=datetime.now() + timedelta(days=30),
                         on_trial=True),
             domain='localhost', template_folder='example.com')
    ]
    for tenant in tenants:
        t = Tenant.objects.create(**tenant['tenant'])
        Domain.objects.create(domain=tenant['domain'], tenant=t)
        Site.objects.create(domain=tenant['domain'], name=tenant['template_folder'])


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0003_tenant_template_dir_name'),
        ('multitenancy', '0003_tenant_s3_bucket_name'),
    ]

    operations = [
        migrations.RunPython(add_default_tenant)
    ]
