# Generated by Django 2.2.5 on 2021-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0002_auto_20200306_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='s3_bucket_name',
            field=models.CharField(default='demo-bucket', max_length=100),
        ),
    ]
