# Generated by Django 2.2.5 on 2021-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0002_auto_20200306_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='template_dir_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
