# Generated by Django 2.2.5 on 2020-06-01 08:23

import oscar.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='price_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
    ]
