# Generated by Django 2.2.5 on 2020-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymentmethod_signing_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('number', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Order number')),
            ],
        ),
    ]
