# Generated by Django 3.2.23 on 2024-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paypaltransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['pk'], 'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['name'], 'verbose_name': 'Source Type', 'verbose_name_plural': 'Source Types'},
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Name'),
        ),
    ]
