# Generated by Django 3.2.25 on 2025-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20240113_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='charges',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cash on Delivery charges are non refundable.', max_digits=10, verbose_name='COD Charges'),
        ),
    ]
